package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.ctre.phoenix6.swerve.SwerveRequest.ForwardPerspectiveValue;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import com.pathplanner.lib.util.PathPlannerLogging;
import edu.wpi.first.math.Pair;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.units.measure.AngularVelocity;
import edu.wpi.first.units.measure.LinearVelocity;
import edu.wpi.first.util.sendable.Sendable;
import edu.wpi.first.util.sendable.SendableBuilder;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.CommandScheduler;
import edu.wpi.first.wpilibj2.command.FunctionalCommand;
import edu.wpi.first.wpilibj2.command.InstantCommand;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Constants;
import frc.robot.generated.WoodBotDrivetrain.TunerSwerveDrivetrain;
import frc.robot.lib.BLine.FollowPath;
import frc.robot.subsystems.Vision.VisionMeasurement;
import frc.robot.utils.AllianceFlipUtil;
import frc.robot.utils.ControllerHelper;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.DoubleSupplier;
import java.util.function.Supplier;
import org.littletonrobotics.junction.Logger;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements Subsystem so it can easily
 * be used in command-based projects.
 *
 * <p>Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
  public final LinearVelocity maxSpeed = Constants.getMaxSpeed();
  private AngularVelocity maxAngularVelocity = Constants.getMaxAngularVelocity();
  private boolean isDefenseMode = false;
  private static final double kSimLoopPeriod = 0.004; // 4 ms
  private Notifier m_simNotifier = null;
  private double m_lastSimTime;
  private static final String SUBSYSTEM_NAME = "Swerve/";
  private final SwerveRequest xOutReq = new SwerveRequest.SwerveDriveBrake();
  private final Field2d field = new Field2d();

  // Keep track of when vision measurements are added for logging context
  private boolean hasVisionMeasurements = false;

  // Lazily-cached state copy. Invalidated once per cycle via clearCachedState() in
  // preSchedulerUpdate(), then populated on first access via getCachedState().
  // This ensures at most one getStateCopy() allocation per scheduler cycle.
  private SwerveDriveState cachedState;

  // Commanded speeds for shoot-on-the-move compensation (tracks what we tell the robot to do)
  private ChassisSpeeds commandedSpeeds = new ChassisSpeeds();

  /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
  private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
  /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
  private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
  /* Keep track if we've ever applied the operator perspective before or not */
  private boolean m_hasAppliedOperatorPerspective = false;

  // Apply Robot Speeds
  private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds =
      new SwerveRequest.ApplyRobotSpeeds();

  /* Swerve requests to apply during SysId characterization */
  private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization =
      new SwerveRequest.SysIdSwerveTranslation();
  private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization =
      new SwerveRequest.SysIdSwerveSteerGains();
  private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization =
      new SwerveRequest.SysIdSwerveRotation();
  private final DriveRequestType m_driveRequestType = DriveRequestType.Velocity;

  // Heading controller PID gains (from example code)
  private static final double HEADING_KP = 14.0;
  private static final double HEADING_KI = 0.1;
  private static final double HEADING_KD = 0.5; // 1.0 Kd is prob the highest we should go
  private static final double HEADING_I_ZONE = Math.toRadians(10.0);
  private static final double HEADING_TOLERANCE_RAD = Math.toRadians(5.0);
  private final double HEADING_INTEGRATOR_MAX_RAD_PER_S =
      Constants.getMaxAngularVelocity().in(RadiansPerSecond) * 0.5;
  // Extra heading tolerance granted per m/s of translational speed.
  // Compensates for the PID steady-state tracking lag when the heading setpoint moves
  // (setpoint rate ≈ v/d rad/s; lag ≈ rate/KP). Tunable — start at ~5°/m/s.
  private static final double HEADING_SPEED_TOLERANCE_RAD_PER_MPS = Math.toRadians(1.0);

  // Maximum translational speed while using field-centric facing angle (fraction of maxSpeed).
  // Limits how much shoot-on-the-move compensation is needed.
  private static final double FACING_ANGLE_MAX_SPEED_FRACTION = 0.5;
  private static final double CONTROLLER_DEADBAND = 0.04;

  // Heading lock state for driver-assist toggle
  private boolean headingLockEnabled = false;
  private double currentTargetAngle = 0.0;
  private boolean headingControllerActive =
      false; // Tracks if facing-angle request has been applied
  private static final double SNAP_THRESHOLD = 0.3; // High tolerance to prevent accidental presses

  private enum SnapDirection {
    NONE,
    UP,
    DOWN,
    LEFT,
    RIGHT
  }

  private SnapDirection previousSnapDirection = SnapDirection.NONE;

  // Called once per scheduler cycle from fieldOrientedDriveCommand to update the snap target.
  // Kept outside the applyRequest lambda so it runs exactly once per cycle regardless of
  // how many times the request supplier is invoked.
  private void updateSnapAngle(double rightX, double rightY) {
    boolean yDominant = Math.abs(rightY) >= Math.abs(rightX);
    boolean pushUp = yDominant && rightY < -SNAP_THRESHOLD;
    boolean pushDown = yDominant && rightY > SNAP_THRESHOLD;
    boolean pushRight = !yDominant && rightX > SNAP_THRESHOLD;
    boolean pushLeft = !yDominant && rightX < -SNAP_THRESHOLD;

    SnapDirection currentSnapDirection;
    if (pushUp) currentSnapDirection = SnapDirection.UP;
    else if (pushDown) currentSnapDirection = SnapDirection.DOWN;
    else if (pushRight) currentSnapDirection = SnapDirection.RIGHT;
    else if (pushLeft) currentSnapDirection = SnapDirection.LEFT;
    else currentSnapDirection = SnapDirection.NONE;

    if (currentSnapDirection == previousSnapDirection) return;
    previousSnapDirection = currentSnapDirection;

    // Blue-perspective base angles flipped automatically for Red via AllianceFlipUtil:
    //   up=0°, down=180°, right=270°, left=90°
    switch (currentSnapDirection) {
      case UP ->
          currentTargetAngle = AllianceFlipUtil.apply(Rotation2d.fromDegrees(0.0)).getDegrees();
      case DOWN ->
          currentTargetAngle = AllianceFlipUtil.apply(Rotation2d.fromDegrees(180.0)).getDegrees();
      case RIGHT ->
          currentTargetAngle = AllianceFlipUtil.apply(Rotation2d.fromDegrees(270.0)).getDegrees();
      case LEFT ->
          currentTargetAngle = AllianceFlipUtil.apply(Rotation2d.fromDegrees(90.0)).getDegrees();
      case NONE -> {}
    }
  }

  // Field-centric facing angle request for hub tracking
  private final SwerveRequest.FieldCentricFacingAngle angleFacingRequest =
      new SwerveRequest.FieldCentricFacingAngle()
          .withDeadband(maxSpeed.in(MetersPerSecond) * CONTROLLER_DEADBAND)
          .withRotationalDeadband(0.0)
          .withDriveRequestType(m_driveRequestType); // No deadband for rotation when facing point

  public final Command fieldOrientedDriveCommand(
      CommandXboxController driveCont) { // field oriented drive command!
    SwerveRequest.FieldCentric drive =
        new SwerveRequest.FieldCentric() // creates a fieldcentric drive
            .withDeadband(maxSpeed.in(MetersPerSecond) * CONTROLLER_DEADBAND)
            .withRotationalDeadband(maxAngularVelocity.in(RadiansPerSecond) * CONTROLLER_DEADBAND)
            .withDriveRequestType(m_driveRequestType);
    double defenseModeRotationScaler = 1.25;
    double defenseModeTranslationScaler = 0.75;
    return this.applyRequest(
        () -> {
          double velXMps =
              -ControllerHelper.modifyAxisCubic(driveCont.getLeftY(), maxSpeed.in(MetersPerSecond));
          double velYMps =
              -ControllerHelper.modifyAxisCubic(driveCont.getLeftX(), maxSpeed.in(MetersPerSecond));
          double omegaRps =
              -ControllerHelper.modifyAxisSquared(
                  driveCont.getRightX(), maxAngularVelocity.in(RadiansPerSecond));
          if (isDefenseMode) {
            velXMps *= defenseModeTranslationScaler;
            velYMps *= defenseModeTranslationScaler;
            omegaRps *= defenseModeRotationScaler;
          }
          // Store as robot-relative to match getVelocity() convention.
          // Operator-perspective velocities are converted to field-relative via
          // alliance flip, then to robot-relative via fromFieldRelativeSpeeds.
          boolean isBlueAlliance =
              DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Blue;
          commandedSpeeds =
              ChassisSpeeds.fromFieldRelativeSpeeds(
                  isBlueAlliance ? velXMps : -velXMps,
                  isBlueAlliance ? velYMps : -velYMps,
                  headingLockEnabled && headingControllerActive
                      ? angleFacingRequest.HeadingController.getLastAppliedOutput()
                      : omegaRps,
                  getPosition().getRotation());

          if (headingLockEnabled) {
            updateSnapAngle(driveCont.getRightX(), driveCont.getRightY());
            headingControllerActive = true; // Mark that we've applied the facing-angle request
            return angleFacingRequest
                .withVelocityX(isBlueAlliance ? velXMps : -velXMps)
                .withVelocityY(isBlueAlliance ? velYMps : -velYMps)
                .withTargetDirection(Rotation2d.fromDegrees(currentTargetAngle));
          }

          return drive
              .withVelocityX(velXMps) // Drive forward with negative Y (forward)
              .withVelocityY(velYMps) // Drive left with negative X (left)
              .withRotationalRate(omegaRps); // Drive
        }
        // counterclockwise
        // with negative X
        // (left)
        );
  }

  private final SwerveRequest.FieldCentric FIELD_CENTRIC_DRIVE =
      new SwerveRequest.FieldCentric()
          .withDeadband(maxSpeed.in(MetersPerSecond) * CONTROLLER_DEADBAND)
          .withRotationalDeadband(maxAngularVelocity.in(RadiansPerSecond) * CONTROLLER_DEADBAND)
          .withDriveRequestType(m_driveRequestType);

  // defense mode command
  private void toggleDefenseMode() {
    isDefenseMode = !isDefenseMode;
  }

  public Command toggleDefenseModeCmd() {
    return this.runOnce(() -> toggleDefenseMode());
  }

  // Xout Command
  public void xOut() {
    commandedSpeeds.vxMetersPerSecond = 0.0;
    commandedSpeeds.vyMetersPerSecond = 0.0;
    commandedSpeeds.omegaRadiansPerSecond = 0.0;
    this.setControl(xOutReq);
  }

  public Command xOutCmd() {
    return this.run(() -> xOut());
  }

  public Command toggleHeadingLockCommand() {
    return new InstantCommand(
        () -> {
          headingLockEnabled = !headingLockEnabled;
          headingControllerActive = false; // Reset so we know when fresh data is available
          if (headingLockEnabled) {
            angleFacingRequest.HeadingController.reset();
            // Initialize to nearest 90° angle when enabling
            double currentDegrees = getRotation2d().getDegrees();
            currentDegrees = ((currentDegrees % 360) + 360) % 360;
            currentTargetAngle = Math.round(currentDegrees / 90.0) * 90.0;
            if (currentTargetAngle >= 360) currentTargetAngle = 0;
          }
        });
  }

  public boolean isHeadingLockEnabled() {
    return headingLockEnabled;
  }

  /**
   * Drives the robot in field-centric mode while continuously rotating to face the given heading.
   * Velocities are field-relative (already alliance-flipped by the caller). The caller is
   * responsible for resetting the heading controller when done.
   *
   * @param fieldRelativeVelXMps X velocity in m/s (field-relative, already alliance-flipped)
   * @param fieldRelativeVelYMps Y velocity in m/s (field-relative, already alliance-flipped)
   * @param targetHeading The target heading to face
   */
  public void faceAngleWhileDriving(
      double fieldRelativeVelXMps, double fieldRelativeVelYMps, Rotation2d targetHeading) {
    double speedCapMps = maxSpeed.in(MetersPerSecond) * FACING_ANGLE_MAX_SPEED_FRACTION;

    // Clamp the velocity vector magnitude to the speed cap
    double rawSpeedMps = Math.hypot(fieldRelativeVelXMps, fieldRelativeVelYMps);
    if (rawSpeedMps > speedCapMps) {
      double scale = speedCapMps / rawSpeedMps;
      fieldRelativeVelXMps *= scale;
      fieldRelativeVelYMps *= scale;
    }

    double omegaRps = angleFacingRequest.HeadingController.getLastAppliedOutput();

    // Store as robot-relative to match getVelocity() convention.
    commandedSpeeds =
        ChassisSpeeds.fromFieldRelativeSpeeds(
            fieldRelativeVelXMps, fieldRelativeVelYMps, omegaRps, getPosition().getRotation());

    this.setControl(
        angleFacingRequest
            .withVelocityX(fieldRelativeVelXMps)
            .withVelocityY(fieldRelativeVelYMps)
            .withTargetDirection(targetHeading));
  }

  /**
   * Creates a command that drives the robot in field-centric mode while continuously rotating to
   * face the given heading.
   *
   * @param velocityXSupplier Supplier for X velocity (operator-perspective, forward positive) in
   *     m/s
   * @param velocityYSupplier Supplier for Y velocity (operator-perspective, left positive) in m/s
   * @param headingSupplier Supplier for the target heading
   * @return Command that drives while facing the heading
   */
  public Command faceAngleWhileDrivingCommand(
      DoubleSupplier velocityXSupplier,
      DoubleSupplier velocityYSupplier,
      Supplier<Rotation2d> headingSupplier) {
    return new FunctionalCommand(
        () -> {
          angleFacingRequest.HeadingController.reset();
          angleFacingRequest.withTargetDirection(headingSupplier.get());
        },
        () -> {
          double rawVelXMps = velocityXSupplier.getAsDouble();
          double rawVelYMps = velocityYSupplier.getAsDouble();

          boolean isBlueAlliance =
              DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Blue;
          double fieldVelXMps = isBlueAlliance ? rawVelXMps : -rawVelXMps;
          double fieldVelYMps = isBlueAlliance ? rawVelYMps : -rawVelYMps;

          faceAngleWhileDriving(fieldVelXMps, fieldVelYMps, headingSupplier.get());
        },
        interrupted -> angleFacingRequest.HeadingController.reset(),
        () -> false,
        this);
  }

  /**
   * Creates a command that drives the robot in field-centric mode while continuously rotating to
   * face the hub center, using controller input with cubic response curve.
   *
   * @param driveCont The Xbox controller for driver input
   * @return Command that drives while facing the hub
   */
  public Command faceAngleWhileDrivingCommand(
      CommandXboxController driveCont, Supplier<Rotation2d> headingSupplier) {
    return faceAngleWhileDrivingCommand(
        () -> -ControllerHelper.modifyAxisCubic(driveCont.getLeftY(), maxSpeed.in(MetersPerSecond)),
        () -> -ControllerHelper.modifyAxisCubic(driveCont.getLeftX(), maxSpeed.in(MetersPerSecond)),
        headingSupplier);
  }

  /*
   * SysId routine for characterizing translation. This is used to find PID gains
   * for the drive motors.
   */
  private final SysIdRoutine m_sysIdRoutineTranslation =
      new SysIdRoutine(
          new SysIdRoutine.Config(
              null, // Use default ramp rate (1 V/s)
              Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
              null, // Use default timeout (10 s)
              // Log state with SignalLogger class
              state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())),
          new SysIdRoutine.Mechanism(
              output -> setControl(m_translationCharacterization.withVolts(output)), null, this));

  /*
   * SysId routine for characterizing steer. This is used to find PID gains for
   * the steer motors.
   */
  private final SysIdRoutine m_sysIdRoutineSteer =
      new SysIdRoutine(
          new SysIdRoutine.Config(
              null, // Use default ramp rate (1 V/s)
              Volts.of(7), // Use dynamic voltage of 7 V
              null, // Use default timeout (10 s)
              // Log state with SignalLogger class
              state -> SignalLogger.writeString("SysIdSteer_State", state.toString())),
          new SysIdRoutine.Mechanism(
              volts -> setControl(m_steerCharacterization.withVolts(volts)), null, this));

  /*
   * SysId routine for characterizing rotation.
   * This is used to find PID gains for the FieldCentricFacingAngle
   * HeadingController.
   * See the documentation of SwerveRequest.SysIdSwerveRotation for info on
   * importing the log to SysId.
   */
  private final SysIdRoutine m_sysIdRoutineRotation =
      new SysIdRoutine(
          new SysIdRoutine.Config(
              /* This is in radians per second², but SysId only supports "volts per second" */
              Volts.of(Math.PI / 6).per(Second),
              /* This is in radians per second, but SysId only supports "volts" */
              Volts.of(Math.PI),
              null, // Use default timeout (10 s)
              // Log state with SignalLogger class
              state -> SignalLogger.writeString("SysIdRotation_State", state.toString())),
          new SysIdRoutine.Mechanism(
              output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
              },
              null,
              this));

  /* The SysId routine to test */
  private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants, SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, modules);
    // Registers the subsystem so periodic runs
    CommandScheduler.getInstance().registerSubsystem(this);
    angleFacingRequest.HeadingController.setPID(HEADING_KP, HEADING_KI, HEADING_KD);
    angleFacingRequest.HeadingController.enableContinuousInput(-Math.PI, Math.PI);
    angleFacingRequest.HeadingController.setIZone(HEADING_I_ZONE);
    angleFacingRequest.HeadingController.setIntegratorRange(
        -HEADING_INTEGRATOR_MAX_RAD_PER_S, HEADING_INTEGRATOR_MAX_RAD_PER_S);
    angleFacingRequest.HeadingController.setTolerance(HEADING_TOLERANCE_RAD);
    angleFacingRequest.ForwardPerspective = ForwardPerspectiveValue.BlueAlliance;
    if (Utils.isSimulation()) {
      startSimThread();
    }
    configureAutoBuilder();
    configureAutoLogging();
    SmartDashboard.putData("Field", field);
    SmartDashboard.putData(
        "Swerve Drive",
        new Sendable() {
          @Override
          public void initSendable(SendableBuilder builder) {
            builder.setSmartDashboardType("SwerveDrive");

            // Use cached state from periodic() to avoid multiple getStateCopy() calls
            // Front Left (Module 0)
            builder.addDoubleProperty(
                "Front Left Angle",
                () -> cachedState != null ? cachedState.ModuleStates[0].angle.getRadians() : 0.0,
                null);
            builder.addDoubleProperty(
                "Front Left Velocity",
                () -> cachedState != null ? cachedState.ModuleStates[0].speedMetersPerSecond : 0.0,
                null);

            // Front Right (Module 1)
            builder.addDoubleProperty(
                "Front Right Angle",
                () -> cachedState != null ? cachedState.ModuleStates[1].angle.getRadians() : 0.0,
                null);
            builder.addDoubleProperty(
                "Front Right Velocity",
                () -> cachedState != null ? cachedState.ModuleStates[1].speedMetersPerSecond : 0.0,
                null);

            // Back Left (Module 2)
            builder.addDoubleProperty(
                "Back Left Angle",
                () -> cachedState != null ? cachedState.ModuleStates[2].angle.getRadians() : 0.0,
                null);
            builder.addDoubleProperty(
                "Back Left Velocity",
                () -> cachedState != null ? cachedState.ModuleStates[2].speedMetersPerSecond : 0.0,
                null);

            // Back Right (Module 3)
            builder.addDoubleProperty(
                "Back Right Angle",
                () -> cachedState != null ? cachedState.ModuleStates[3].angle.getRadians() : 0.0,
                null);
            builder.addDoubleProperty(
                "Back Right Velocity",
                () -> cachedState != null ? cachedState.ModuleStates[3].speedMetersPerSecond : 0.0,
                null);

            // Robot angle
            builder.addDoubleProperty(
                "Robot Angle", () -> getCachedState().Pose.getRotation().getRadians(), null);
          }
        });
  }

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set to
   *     0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
   * @param modules Constants for each specific module
   */

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set to
   *     0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
   * @param odometryStandardDeviation The standard deviation for odometry calculation in the form
   *     [x, y, theta]ᵀ, with units in meters and radians
   * @param visionStandardDeviation The standard deviation for vision calculation in the form [x, y,
   *     theta]ᵀ, with units in meters and radians
   * @param modules Constants for each specific module
   */
  // PathPlanner AutoBuilder PID gains
  private static final double PP_TRANSLATION_KP = 11.0;

  private static final double PP_TRANSLATION_KI = 0.0;
  private static final double PP_TRANSLATION_KD = 0.0;
  private static final double PP_ROTATION_KP = 8.0;
  private static final double PP_ROTATION_KI = 0.0;
  private static final double PP_ROTATION_KD = 0.0;

  private void configureAutoBuilder() {
    try {
      RobotConfig config;
      // TODO rework this so it's unified with the top level robot builder class
      if (Constants.getRobotType() == Constants.RobotType.WOODBOT) {
        config = Constants.WoodBotConstants.createPathPlannerConfig();
      } else {
        config = RobotConfig.fromGUISettings();
      }

      AutoBuilder.configure(
          this::getPosition, // Supplier of current robot pose (uses cached state)
          this::resetPose, // Consumer for seeding pose against auto
          this::getVelocity, // Supplier of current robot speeds (uses cached state)
          // Consumer of ChassisSpeeds and feedforwards to drive the robot
          (speeds, feedforwards) -> {
            setCommandedSpeeds(speeds);
            setControl(
                m_pathApplyRobotSpeeds
                    .withSpeeds(ChassisSpeeds.discretize(speeds, 0.020))
                    .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                    .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())
                    .withDriveRequestType(m_driveRequestType));
          },
          new PPHolonomicDriveController(
              new PIDConstants(PP_TRANSLATION_KP, PP_TRANSLATION_KI, PP_TRANSLATION_KD),
              new PIDConstants(PP_ROTATION_KP, PP_ROTATION_KI, PP_ROTATION_KD)),
          config,
          // Assume the path needs to be flipped for Red vs Blue, this is normally the
          // case
          () -> false,
          this // Subsystem for requirements
          );
    } catch (Exception ex) {
      DriverStation.reportError(
          "Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
    }
  }

  // Key cache for BLine logging — populated once per unique BLine key, reused every loop.
  private final Map<String, String> blineKeyCache = new HashMap<>();

  private String blineKey(String rawKey) {
    return blineKeyCache.computeIfAbsent(
        rawKey, k -> "Autos/BLine/" + k.replace("FollowPath/", ""));
  }

  private void configureAutoLogging() {
    // PathPlanner — log under Autos/PathPlanner/
    PathPlannerLogging.setLogCurrentPoseCallback(
        pose -> Logger.recordOutput("Autos/PathPlanner/currentPose", pose));
    PathPlannerLogging.setLogTargetPoseCallback(
        pose -> Logger.recordOutput("Autos/PathPlanner/targetPose", pose));
    PathPlannerLogging.setLogActivePathCallback(
        path -> Logger.recordOutput("Autos/PathPlanner/activePath", path.toArray(new Pose2d[0])));

    // BLine — log under Autos/BLine/; keys are interned via blineKeyCache on first use
    FollowPath.setPoseLoggingConsumer(
        (Pair<String, edu.wpi.first.math.geometry.Pose2d> pair) ->
            Logger.recordOutput(blineKey(pair.getFirst()), pair.getSecond()));
    FollowPath.setTranslationListLoggingConsumer(
        (Pair<String, edu.wpi.first.math.geometry.Translation2d[]> pair) ->
            Logger.recordOutput(blineKey(pair.getFirst()), pair.getSecond()));
    FollowPath.setBooleanLoggingConsumer(
        (Pair<String, Boolean> pair) ->
            Logger.recordOutput(blineKey(pair.getFirst()), pair.getSecond()));
    FollowPath.setDoubleLoggingConsumer(
        (Pair<String, Double> pair) ->
            Logger.recordOutput(blineKey(pair.getFirst()), pair.getSecond()));
  }

  // BLine AutoBuilder PID gains — initial values derived from PathPlanner tuning.
  // Translation/rotation are intentionally lower than PP since BLine's controller
  // semantics differ (distance-to-goal vs time-parameterized).
  private static final double BLINE_TRANSLATION_KP = 5.0;
  private static final double BLINE_TRANSLATION_KI = 0.0;
  private static final double BLINE_TRANSLATION_KD = 0.0;
  private static final double BLINE_ROTATION_KP = 3.0;
  private static final double BLINE_ROTATION_KI = 0.0;
  private static final double BLINE_ROTATION_KD = 0.0;
  private static final double BLINE_CROSS_TRACK_KP = 2.5;
  private static final double BLINE_CROSS_TRACK_KI = 0.0;
  private static final double BLINE_CROSS_TRACK_KD = 0.0;

  /**
   * Creates a reusable BLine FollowPath.Builder configured for this drivetrain. The builder can be
   * used to construct path-following commands via {@code builder.build(path)}.
   *
   * @return a configured {@link FollowPath.Builder}
   */
  public FollowPath.Builder createBLinePathBuilder() {
    return new FollowPath.Builder(
            this,
            this::getPosition,
            this::getVelocity,
            this::driveRobotRelative,
            new PIDController(BLINE_TRANSLATION_KP, BLINE_TRANSLATION_KI, BLINE_TRANSLATION_KD),
            new PIDController(BLINE_ROTATION_KP, BLINE_ROTATION_KI, BLINE_ROTATION_KD),
            new PIDController(BLINE_CROSS_TRACK_KP, BLINE_CROSS_TRACK_KI, BLINE_CROSS_TRACK_KD))
        .withPoseReset(this::resetPose);
  }

  /**
   * Drives the robot with the given robot-relative chassis speeds. Used as the drive consumer for
   * BLine path following (no feedforwards — BLine doesn't provide them).
   *
   * @param speeds robot-relative chassis speeds
   */
  public void driveRobotRelative(ChassisSpeeds speeds) {
    setCommandedSpeeds(speeds);
    setControl(
        m_pathApplyRobotSpeeds
            .withSpeeds(ChassisSpeeds.discretize(speeds, 0.020))
            .withDriveRequestType(m_driveRequestType));
  }

  /**
   * Returns the lazily-cached swerve state for this scheduler cycle. On the first call after {@link
   * #clearCachedState()}, this calls {@link #getStateCopy()} once and caches the result. All
   * subsequent calls in the same cycle return the cached instance with zero allocation.
   *
   * @return the cached {@link SwerveDriveState}
   */
  public SwerveDriveState getCachedState() {
    if (cachedState == null) {
      cachedState = this.getStateCopy();
    }
    return cachedState;
  }

  /**
   * Invalidates the cached swerve state so the next {@link #getCachedState()} call fetches a fresh
   * copy. Called once per scheduler cycle from {@link
   * frc.robot.RobotContainer#preSchedulerUpdate()}.
   */
  public void clearCachedState() {
    cachedState = null;
  }

  public Pose2d getPose2d() {
    return getCachedState().Pose;
  }

  public Rotation2d getRotation2d() {
    return getCachedState().Pose.getRotation();
  }

  /**
   * Returns whether the heading controller is aligned to its target angle within a speed-scaled
   * tolerance. Uses the {@link com.ctre.phoenix6.swerve.utility.PhoenixPIDController#atSetpoint()}
   * method on the facing-angle request's heading controller.
   *
   * <p>The tolerance grows with translational speed to account for the PID steady-state tracking
   * lag: when the robot moves, the heading setpoint changes at roughly {@code v/d} rad/s, producing
   * a lag of {@code (v/d)/KP} rad. Adding {@link #HEADING_SPEED_TOLERANCE_RAD_PER_MPS} per m/s
   * compensates for this so the robot can fire during shoot-on-the-move.
   *
   * <p>Note: This only returns meaningful results while a {@link
   * SwerveRequest.FieldCentricFacingAngle} request is actively being applied (e.g., during
   * faceAngleWhileDriving). Before the first PID calculation, this returns false.
   *
   * @return true if the heading error is within the speed-scaled tolerance
   */
  public boolean isAlignedToTarget() {
    ChassisSpeeds speeds = getVelocity();
    double speedMps = Math.hypot(speeds.vxMetersPerSecond, speeds.vyMetersPerSecond);
    double dynamicToleranceRad =
        HEADING_TOLERANCE_RAD + speedMps * HEADING_SPEED_TOLERANCE_RAD_PER_MPS;
    Logger.recordOutput(
        SUBSYSTEM_NAME + "DynamicHeadingToleranceDeg", Math.toDegrees(dynamicToleranceRad));

    angleFacingRequest.HeadingController.setTolerance(dynamicToleranceRad);
    return angleFacingRequest.HeadingController.atSetpoint();
  }

  /** Resets the facing-angle heading controller so it must re-converge from scratch. */
  public void resetHeadingController() {
    angleFacingRequest.HeadingController.reset();
  }

  /**
   * Returns the configured heading tolerance in radians.
   *
   * @return heading tolerance in radians
   */
  public double getHeadingToleranceRad() {
    return HEADING_TOLERANCE_RAD;
  }

  public double getAngle() {
    return getRotation2d().getDegrees();
  }

  public double getAngularRate() {
    return Math.toDegrees(getVelocity().omegaRadiansPerSecond);
  }

  public void zero() {
    this.tareEverything();
  }

  public Command zeroCommand() {
    return this.runOnce(() -> zero());
  }

  /**
   * Returns a command that applies the specified control request to this swerve drivetrain.
   *
   * @param request Function returning the request to apply
   * @return Command to run
   */
  public Command applyRequest(Supplier<SwerveRequest> request) {
    return run(() -> this.setControl(request.get()));
  }

  /**
   * Runs the SysId Quasistatic test in the given direction for the routine specified by {@link
   * #m_sysIdRoutineToApply}.
   *
   * @param direction Direction of the SysId Quasistatic test
   * @return Command to run
   */
  public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
    return m_sysIdRoutineToApply.quasistatic(direction);
  }

  /**
   * Runs the SysId Dynamic test in the given direction for the routine specified by {@link
   * #m_sysIdRoutineToApply}.
   *
   * @param direction Direction of the SysId Dynamic test
   * @return Command to run
   */
  public Command sysIdDynamic(SysIdRoutine.Direction direction) {
    return m_sysIdRoutineToApply.dynamic(direction);
  }

  @Override
  public void periodic() {
    SwerveDriveState state = getCachedState();

    field.setRobotPose(state.Pose);

    Logger.recordOutput(SUBSYSTEM_NAME + "CurrentPose", state.Pose);
    Logger.recordOutput(SUBSYSTEM_NAME + "Rotation2d", state.RawHeading);
    Logger.recordOutput(SUBSYSTEM_NAME + "CurrentState", state.ModuleStates);
    Logger.recordOutput(SUBSYSTEM_NAME + "TargetState", state.ModuleTargets);
    Logger.recordOutput(SUBSYSTEM_NAME + "Using Vision", hasVisionMeasurements);
    Logger.recordOutput(SUBSYSTEM_NAME + "Is Defense Mode", isDefenseMode);
    Logger.recordOutput(
        SUBSYSTEM_NAME + "HeadingSetpointDeg",
        Math.toDegrees(angleFacingRequest.HeadingController.getSetpoint()));

    // Log whether vision measurements have been applied (useful for analysis)
    /*
     * Periodically try to apply the operator perspective.
     * If we haven't applied the operator perspective before, then we should apply
     * it regardless of DS state.
     * This allows us to correct the perspective in case the robot code restarts
     * mid-match.
     * Otherwise, only check and apply the operator perspective if the DS is
     * disabled.
     * This ensures driving behavior doesn't change until an explicit disable event
     * occurs during testing.
     */

    if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
      DriverStation.getAlliance()
          .ifPresent(
              allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
              });
    }
  }

  private void startSimThread() {
    // prevents the method from running multiple times
    if (m_simNotifier != null) {
      return;
    }

    m_lastSimTime = Utils.getCurrentTimeSeconds();

    /* Run simulation at a faster rate so PID gains behave more reasonably */
    m_simNotifier =
        new Notifier(
            () -> {
              final double currentTime = Utils.getCurrentTimeSeconds();
              double deltaTime = currentTime - m_lastSimTime;
              m_lastSimTime = currentTime;

              /* use the measured time delta, get battery voltage from WPILib */
              updateSimState(deltaTime, RobotController.getBatteryVoltage());
            });
    m_simNotifier.startPeriodic(kSimLoopPeriod);
  }

  public void addVisionMeasurements(List<VisionMeasurement> measurements) {
    // Update vision status based on whether we have measurements this cycle
    hasVisionMeasurements = !measurements.isEmpty();

    for (VisionMeasurement measurement : measurements) {
      this.addVisionMeasurement(
          measurement.estimatedPose(),
          Utils.fpgaToCurrentTime(measurement.timestamp()),
          measurement.standardDeviation());
    }
  }

  /**
   * Returns the current estimated pose of the robot on the field.
   *
   * @return the current {@link Pose2d} of the robot
   */
  public Pose2d getPosition() {
    return getCachedState().Pose;
  }

  /**
   * Returns the current chassis speeds of the robot.
   *
   * @return the current {@link ChassisSpeeds} of the robot
   */
  public ChassisSpeeds getVelocity() {
    return getCachedState().Speeds;
  }

  /**
   * Returns the commanded chassis speeds of the robot (what the drivetrain is being told to do).
   * This is less noisy than measured velocities for shoot-on-the-move compensation.
   *
   * @return the commanded {@link ChassisSpeeds} of the robot
   */
  public ChassisSpeeds getCommandedVelocity() {
    return commandedSpeeds;
  }

  /**
   * Sets the commanded chassis speeds. Called internally when applying drive requests.
   *
   * @param speeds the commanded chassis speeds
   */
  private void setCommandedSpeeds(ChassisSpeeds speeds) {
    this.commandedSpeeds = speeds;
  }

  /**
   * Return the pose at a given timestamp, if the buffer is not empty.
   *
   * @param timestampSeconds The timestamp of the pose in seconds.
   * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
   */
  @Override
  public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
    return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
  }
}
