package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.ctre.phoenix6.swerve.SwerveRequest.ForwardPerspectiveValue;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.units.measure.AngularVelocity;
import edu.wpi.first.units.measure.LinearVelocity;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.CommandScheduler;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.generated.WoodBotDrivetrain.TunerSwerveDrivetrain;
import frc.robot.subsystems.Vision.VisionMeasurement;
import frc.robot.utils.FieldVisualizer;
import java.util.List;
import java.util.Optional;
import java.util.function.DoubleSupplier;
import java.util.function.Supplier;
import org.littletonrobotics.junction.Logger;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements Subsystem so it can easily
 * be used in command-based projects.
 *
 * <p>Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
  private static final double kSimLoopPeriod = 0.004; // 4 ms
  private Notifier m_simNotifier = null;
  private double m_lastSimTime;
  private static final String SUBSYSTEM_NAME = "Swerve/";
  private final SwerveRequest xOutReq = new SwerveRequest.SwerveDriveBrake();

  // Keep track of when vision measurements are added for logging context
  private boolean hasVisionMeasurements = false;

  /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
  private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
  /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
  private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
  /* Keep track if we've ever applied the operator perspective before or not */
  private boolean m_hasAppliedOperatorPerspective = false;

  // Apply Robot Speeds
  private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds =
      new SwerveRequest.ApplyRobotSpeeds();

  /* Swerve requests to apply during SysId characterization */
  private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization =
      new SwerveRequest.SysIdSwerveTranslation();
  private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization =
      new SwerveRequest.SysIdSwerveSteerGains();
  private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization =
      new SwerveRequest.SysIdSwerveRotation();
  private final DriveRequestType m_driveRequestType = DriveRequestType.Velocity;
  // TODO refactor into a constants file
  public static final LinearVelocity maxSpeed = MetersPerSecond.of(4.69);
  public static final AngularVelocity maxAngularVelocity = RevolutionsPerSecond.of(4.0);

  // Heading controller PID gains (from example code)
  private static final double HEADING_KP = 6.0;
  private static final double HEADING_KI = 0.00;
  private static final double HEADING_KD = 0.005;
  private static final double HEADING_I_ZONE = 0.0;
  private static final double HEADING_TOLERANCE_RAD = Math.toRadians(3.0);

  // Field-centric facing angle request for hub tracking
  private final SwerveRequest.FieldCentricFacingAngle m_faceHubRequest =
      new SwerveRequest.FieldCentricFacingAngle()
          .withDeadband(maxSpeed.in(MetersPerSecond) * 0.01)
          .withRotationalDeadband(0.0)
          .withDriveRequestType(m_driveRequestType); // No deadband for rotation when facing point

  public final Command fieldOrientedDriveCommand(
      CommandXboxController driveCont) { // field oriented drive command!
    SwerveRequest.FieldCentric drive =
        new SwerveRequest.FieldCentric() // creates a fieldcentric drive
            .withDeadband(maxSpeed.in(MetersPerSecond) * 0.01)
            .withRotationalDeadband(maxAngularVelocity.in(RadiansPerSecond) * 0.01)
            .withDriveRequestType(m_driveRequestType);
    return this.applyRequest(
        () ->
            drive
                .withVelocityX(
                    Math.pow(driveCont.getLeftY(), 3)
                        * maxSpeed.in(MetersPerSecond)
                        * -1.0) // Drive forward with negative Y (forward)
                .withVelocityY(
                    Math.pow(driveCont.getLeftX(), 3)
                        * maxSpeed.in(MetersPerSecond)
                        * -1.0) // Drive left with negative X (left)
                .withRotationalRate(
                    Math.pow(driveCont.getRightX(), 2)
                        * (maxAngularVelocity.in(RadiansPerSecond) / 2.0)
                        * -Math.signum(driveCont.getRightX())) // Drive
        // counterclockwise
        // with negative X
        // (left)
        );
  }

  private final SwerveRequest.FieldCentric FIELD_CENTRIC_DRIVE =
      new SwerveRequest.FieldCentric()
          .withDeadband(maxSpeed.in(MetersPerSecond) * 0.01)
          .withRotationalDeadband(maxAngularVelocity.in(RadiansPerSecond) * 0.01)
          .withDriveRequestType(m_driveRequestType);

  // Xout Command
  public void xOut() {
    this.setControl(xOutReq);
  }

  public Command xOutCmd() {
    return this.applyRequest(() -> xOutReq);
  }

  /**
   * Creates a command that drives the robot in field-centric mode while continuously rotating to
   * face the hub center. The heading controller automatically adjusts the robot's rotation to
   * always point toward the hub as the robot moves around the field.
   *
   * @param velocityXSupplier Supplier for X velocity (field-relative, forward positive) in m/s
   * @param velocityYSupplier Supplier for Y velocity (field-relative, left positive) in m/s
   * @return Command that drives while facing the hub
   */
  public Command faceAngleWhileDrivingCommand(
      DoubleSupplier velocityXSupplier,
      DoubleSupplier velocityYSupplier,
      Supplier<Rotation2d> headingSupplier) {
    return this.applyRequest(
            () ->
                m_faceHubRequest
                    .withVelocityX(
                        DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Blue
                            ? velocityXSupplier.getAsDouble()
                            : -velocityXSupplier.getAsDouble())
                    .withVelocityY(
                        DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Blue
                            ? velocityYSupplier.getAsDouble()
                            : -velocityYSupplier.getAsDouble())
                    .withTargetDirection(headingSupplier.get()))
        .finallyDo(() -> m_faceHubRequest.HeadingController.reset());
  }

  /**
   * Creates a command that drives the robot in field-centric mode while continuously rotating to
   * face the hub center, using controller input with cubic response curve.
   *
   * @param driveCont The Xbox controller for driver input
   * @return Command that drives while facing the hub
   */
  public Command faceAngleWhileDrivingCommand(
      CommandXboxController driveCont, Supplier<Rotation2d> headingSupplier) {
    return faceAngleWhileDrivingCommand(
        () -> Math.pow(driveCont.getLeftY(), 3) * maxSpeed.in(MetersPerSecond) * -1.0,
        () -> Math.pow(driveCont.getLeftX(), 3) * maxSpeed.in(MetersPerSecond) * -1.0,
        headingSupplier);
  }

  /*
   * SysId routine for characterizing translation. This is used to find PID gains
   * for the drive motors.
   */
  private final SysIdRoutine m_sysIdRoutineTranslation =
      new SysIdRoutine(
          new SysIdRoutine.Config(
              null, // Use default ramp rate (1 V/s)
              Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
              null, // Use default timeout (10 s)
              // Log state with SignalLogger class
              state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())),
          new SysIdRoutine.Mechanism(
              output -> setControl(m_translationCharacterization.withVolts(output)), null, this));

  /*
   * SysId routine for characterizing steer. This is used to find PID gains for
   * the steer motors.
   */
  private final SysIdRoutine m_sysIdRoutineSteer =
      new SysIdRoutine(
          new SysIdRoutine.Config(
              null, // Use default ramp rate (1 V/s)
              Volts.of(7), // Use dynamic voltage of 7 V
              null, // Use default timeout (10 s)
              // Log state with SignalLogger class
              state -> SignalLogger.writeString("SysIdSteer_State", state.toString())),
          new SysIdRoutine.Mechanism(
              volts -> setControl(m_steerCharacterization.withVolts(volts)), null, this));

  /*
   * SysId routine for characterizing rotation.
   * This is used to find PID gains for the FieldCentricFacingAngle
   * HeadingController.
   * See the documentation of SwerveRequest.SysIdSwerveRotation for info on
   * importing the log to SysId.
   */
  private final SysIdRoutine m_sysIdRoutineRotation =
      new SysIdRoutine(
          new SysIdRoutine.Config(
              /* This is in radians per second², but SysId only supports "volts per second" */
              Volts.of(Math.PI / 6).per(Second),
              /* This is in radians per second, but SysId only supports "volts" */
              Volts.of(Math.PI),
              null, // Use default timeout (10 s)
              // Log state with SignalLogger class
              state -> SignalLogger.writeString("SysIdRotation_State", state.toString())),
          new SysIdRoutine.Mechanism(
              output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
              },
              null,
              this));

  /* The SysId routine to test */
  private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants, SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, modules);
    // Registers the subsystem so periodic runs
    CommandScheduler.getInstance().registerSubsystem(this);
    m_faceHubRequest.HeadingController.setPID(HEADING_KP, HEADING_KI, HEADING_KD);
    m_faceHubRequest.HeadingController.enableContinuousInput(-Math.PI, Math.PI);
    m_faceHubRequest.HeadingController.setIZone(HEADING_I_ZONE);
    m_faceHubRequest.HeadingController.setTolerance(HEADING_TOLERANCE_RAD);
    m_faceHubRequest.ForwardPerspective = ForwardPerspectiveValue.BlueAlliance;
    if (Utils.isSimulation()) {
      startSimThread();
    }
    configureAutoBuilder();
  }

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set to
   *     0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
   * @param modules Constants for each specific module
   */

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set to
   *     0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
   * @param odometryStandardDeviation The standard deviation for odometry calculation in the form
   *     [x, y, theta]ᵀ, with units in meters and radians
   * @param visionStandardDeviation The standard deviation for vision calculation in the form [x, y,
   *     theta]ᵀ, with units in meters and radians
   * @param modules Constants for each specific module
   */
  private void configureAutoBuilder() {
    try {
      var config = RobotConfig.fromGUISettings();

      AutoBuilder.configure(
          () -> getStateCopy().Pose, // Supplier of current robot pose
          this::resetPose, // Consumer for seeding pose against auto
          () -> getStateCopy().Speeds, // Supplier of current robot speeds
          // Consumer of ChassisSpeeds and feedforwards to drive the robot
          (speeds, feedforwards) ->
              setControl(
                  m_pathApplyRobotSpeeds
                      .withSpeeds(ChassisSpeeds.discretize(speeds, 0.020))
                      .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                      .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())
                      .withDriveRequestType(m_driveRequestType)),
          new PPHolonomicDriveController(
              // PID constants for translation
              new PIDConstants(11, 0, 0),
              // PID constants for rotation
              new PIDConstants(8, 0, 0)),
          config,
          // Assume the path needs to be flipped for Red vs Blue, this is normally the
          // case
          () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
          this // Subsystem for requirements
          );
    } catch (Exception ex) {
      DriverStation.reportError(
          "Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
    }
  }

  public Pose2d getPose2d() {
    return this.getStateCopy().Pose;
  }

  public Rotation2d getRotation2d() {
    return getPose2d().getRotation();
  }

  /**
   * Returns whether the heading controller is aligned to its target angle within the configured
   * tolerance. Uses the {@link com.ctre.phoenix6.swerve.utility.PhoenixPIDController#atSetpoint()}
   * method on the facing-angle request's heading controller.
   *
   * <p>Note: This only returns meaningful results while a {@link
   * SwerveRequest.FieldCentricFacingAngle} request is actively being applied (e.g., during
   * faceAngleWhileDriving). Before the first PID calculation, this returns false.
   *
   * @return true if the heading error is within {@link #HEADING_TOLERANCE_RAD}
   */
  public boolean isAlignedToTarget() {
    return m_faceHubRequest.HeadingController.atSetpoint();
  }

  public double getAngle() {
    return this.getRotation2d().getDegrees();
  }

  public double getAngularRate() {
    return Math.toDegrees(this.getStateCopy().Speeds.omegaRadiansPerSecond);
  }

  public void zero() {
    this.tareEverything();
  }

  public Command zeroCommand() {
    return this.runOnce(() -> zero());
  }

  /**
   * Returns a command that applies the specified control request to this swerve drivetrain.
   *
   * @param request Function returning the request to apply
   * @return Command to run
   */
  public Command applyRequest(Supplier<SwerveRequest> request) {
    return run(() -> this.setControl(request.get()));
  }

  /**
   * Runs the SysId Quasistatic test in the given direction for the routine specified by {@link
   * #m_sysIdRoutineToApply}.
   *
   * @param direction Direction of the SysId Quasistatic test
   * @return Command to run
   */
  public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
    return m_sysIdRoutineToApply.quasistatic(direction);
  }

  /**
   * Runs the SysId Dynamic test in the given direction for the routine specified by {@link
   * #m_sysIdRoutineToApply}.
   *
   * @param direction Direction of the SysId Dynamic test
   * @return Command to run
   */
  public Command sysIdDynamic(SysIdRoutine.Direction direction) {
    return m_sysIdRoutineToApply.dynamic(direction);
  }

  @Override
  public void periodic() {
    // Current pose includes vision fusion when vision measurements are added
    Logger.recordOutput(SUBSYSTEM_NAME + "CurrentPose", this.getStateCopy().Pose);
    Logger.recordOutput(SUBSYSTEM_NAME + "Rotation2d", this.getStateCopy().RawHeading);
    Logger.recordOutput(SUBSYSTEM_NAME + "CurrentState", this.getStateCopy().ModuleStates);
    Logger.recordOutput(SUBSYSTEM_NAME + "TargetState", this.getStateCopy().ModuleTargets);
    Logger.recordOutput(SUBSYSTEM_NAME + "Using Vision", hasVisionMeasurements);

    // Update field visualizations (hub points, line from robot to hub, etc.)
    FieldVisualizer.update(this.getStateCopy().Pose);

    // Log whether vision measurements have been applied (useful for analysis)
    /*
     * Periodically try to apply the operator perspective.
     * If we haven't applied the operator perspective before, then we should apply
     * it regardless of DS state.
     * This allows us to correct the perspective in case the robot code restarts
     * mid-match.
     * Otherwise, only check and apply the operator perspective if the DS is
     * disabled.
     * This ensures driving behavior doesn't change until an explicit disable event
     * occurs during testing.
     */

    if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
      DriverStation.getAlliance()
          .ifPresent(
              allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
              });
    }
  }

  private void startSimThread() {
    // prevents the method from running multiple times
    if (m_simNotifier != null) {
      return;
    }

    m_lastSimTime = Utils.getCurrentTimeSeconds();

    /* Run simulation at a faster rate so PID gains behave more reasonably */
    m_simNotifier =
        new Notifier(
            () -> {
              final double currentTime = Utils.getCurrentTimeSeconds();
              double deltaTime = currentTime - m_lastSimTime;
              m_lastSimTime = currentTime;

              /* use the measured time delta, get battery voltage from WPILib */
              updateSimState(deltaTime, RobotController.getBatteryVoltage());
            });
    m_simNotifier.startPeriodic(kSimLoopPeriod);
  }

  public void addVisionMeasurements(List<VisionMeasurement> measurements) {
    // Update vision status based on whether we have measurements this cycle
    hasVisionMeasurements = !measurements.isEmpty();

    for (VisionMeasurement measurement : measurements) {
      this.addVisionMeasurement(
          measurement.estimatedPose(),
          Utils.fpgaToCurrentTime(measurement.timestamp()),
          measurement.standardDeviation());
    }
  }

  /**
   * Returns the current estimated pose of the robot on the field.
   *
   * @return the current {@link Pose2d} of the robot
   */
  public Pose2d getPosition() {
    return this.getStateCopy().Pose;
  }

  /**
   * Returns the current chassis speeds of the robot.
   *
   * @return the current {@link ChassisSpeeds} of the robot
   */
  public ChassisSpeeds getVelocity() {
    return this.getStateCopy().Speeds;
  }

  /**
   * Return the pose at a given timestamp, if the buffer is not empty.
   *
   * @param timestampSeconds The timestamp of the pose in seconds.
   * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
   */
  @Override
  public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
    return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
  }
}
