flowchart TD
    A[Controller Input] 
    --> B[Sets SuperStructure Wanted State]
    B--> C[current SuperState becomes Wanted SuperState]
    B--> D[Previous SuperState becomes current SuperState]
    C-->E[Based on currentState, sets state of Subsystem]
    ---->F{EX: Collecting Fuel} --> G[Intake wanted state is set to Collecting fuel]
    --> H[Current state is set to wanted state]
    G--> I[Previous state is set to current state]
    H-->J{Checks current state}--state is COLLECTING_FUEL--> K[Sets dutyCycle to 1]
    J -- state is OFF-->L[duty cycle is set to 0/ stop method]